# Form implementation generated from reading ui file 'library_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.query_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.query_box.setGeometry(QtCore.QRect(20, 20, 191, 31))
        self.query_box.setObjectName("query_box")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(20, 80, 231, 31))
        self.searchEdit.setObjectName("searchEdit")
        self.find_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.find_btn.setGeometry(QtCore.QRect(340, 30, 141, 71))
        self.find_btn.setObjectName("find_btn")
        self.result_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(30, 180, 591, 411))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_btn.setText(_translate("MainWindow", "Искать"))
